version: 0.2

phases:
  install:
    commands:
      - echo Installing Ruby 3.1.3...
      - sudo apt-get update
      - sudo apt-get install -y software-properties-common
      - sudo apt-add-repository -y ppa:brightbox/ruby-ng
      - sudo apt-get update
      - sudo apt-get install -y ruby3.1 ruby3.1-dev
      - ruby -v
      - echo Installing Node.js dependencies for the React client
      - cd client
      - npm install
      - cd ..

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Ruby application
      - echo Building the React/TypeScript client
      - cd client
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo Build completed on `date`
