version: 0.2

phases:
  install:
    commands:
      - echo Installing Ruby from source...
      - wget http://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz
      - tar -xzvf ruby-3.1.3.tar.gz
      - cd ruby-3.1.3
      - ./configure
      - make
      - sudo make install
      - ruby -v
      - cd ..
      - echo Installing Node.js dependencies for the React client...
      - cd client
      - npm install
      - cd ..

  pre_build:
    commands:
      - echo Pre-build phase...

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Ruby application
      - echo Building the React/TypeScript client
      - cd client
      - npm run build
      - cd ..

  post_build:
    commands:
      - echo Build completed on `date`
